### PR TITLE
Add support for active record requiring a larger pool size

### PR DESCRIPTION
**Pull request by Geesu**
Overall this change allows for the `pmap` function to update the active record pool size if it is needed (and the active record object is passed during the function call).  This is REQUIRED otherwise we will get "Connection failed after 5 seconds" because the connection pool size won't be large enough.

It changes what is passed directly to the `pmap` function, although it still has support for passing just an integer for legacy code.

The options are:
* `thread_count`
* `active_record_object`

Example function call:
`MyArray.pmap(active_record_object: ActiveRecord::Base, thread_count: 100)`

### CODE REVIEW

**Comment by bruceadams** [comment]
This looks very interesting! :bangbang: Thanks for proposing it! :smile: 

I'm not much of an ActiveRecord user, so it's going to take me some time to wrap my head around it all.

**Comment by bruceadams** [comment]
@shepmaster can you take a look at this pull request?

**Comment by bruceadams** [comment]
Am I understanding correctly that the whole point of this set of changes is to _change_ the connection pool size?

Changing a connection pool size at run time goes against everything I've ever understood about sizing database connection pools. Connection pool size has external impact, specifically how many connections the database engine (such as Postgres) needs to be able to handle. The maximum size of an application's connection pool needs to be top level configuration information (so a database administrator can easily check what it is set to) and that maximum size needs to be respected at all times (to avoid overrunning the database engine).

**Comment by Geesu** [comment]
If you don't change the size of the pool you will run out of connections.  Just try having 2 threads with an active record object in each that does a select.  One will fail every time.

This pull request addresses that, we've been running it in production for quite some time.  And we actually had a home grown threading solution running for the past 2 years ish that did that same thing.

**Comment by bruceadams** [comment]
I am completely confused. Why does the connection pool size need to be changed on the fly? Why not just make pool larger in the usual place: `config/database.yml`.

**Comment by Geesu** [comment]
You are correct in that making this change on the fly (not in the yml file) is sketchy, but I wasn't sure how else to do this.

Originally we changed the pool size at the end of the database url but it would fail for new threads. This change will ensure you have enough for the threads.

But the programmer needs to be aware of the limitations, which is why they have to explicitly set it.

**Comment by davidbiehl** [comment]
I'm not going to argue about changing the connection_pol size, but I think this should be a separate gem. There are many projects that use pmap that may not necessarily use active record. Adding the dependency to active record confuses the purpose of this gem, even if it's safe by checking for it.

Now that threads are managed in their own `ThreadPool` class, we can create a new thread pool strategy that manages the connection pool. Maybe pmap should support a default ThreadPool configuration like so:

```
PMap.configure do |config|
  config.default_thread_pool_class = ActiveRecordThreadPool
end
```

Then it would use the `ActiveRecordThreadPool` which would manage the connection pool, and we don't have to confuse the intent of the pure pmap gem.

**Pull request closed without merging**
